### ISSUE TITLE
Reset Heading Button

### ISSUE THREAD

**Issue by Jvader314** [Team2338/Reprogram2020_A#1]
This will be done through shuffleboard (smartdashboard).

**Comment by billknopfjr** [comment]
Create a button on the dashboard which will reset the pigeon heading to 0 degrees, resets the encoders, and resets the Pose.

**Comment by billknopfjr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/UCAAfVHf/1-test)
